
[2020-05-12 16:40:04] skeletonlog.ERROR: Uncaught Exception Error: "Class 'Kptask\User\Validator\UserValidator' not found" at /vagrant/kptask/config/bootstrap.php line 189 {"exception":"[object] (Error(code: 0): Class 'Kptask\\User\\Validator\\UserValidator' not found at /vagrant/kptask/config/bootstrap.php:189)"} []
[2020-05-12 16:57:58] skeletonlog.ERROR: Uncaught Exception Error: "Class 'Kptask\User\Validator\UserValidator' not found" at /vagrant/kptask/config/bootstrap.php line 189 {"exception":"[object] (Error(code: 0): Class 'Kptask\\User\\Validator\\UserValidator' not found at /vagrant/kptask/config/bootstrap.php:189)"} []
[2020-05-12 17:00:35] skeletonlog.ALERT: Fatal Error (E_COMPILE_ERROR): Declaration of Kptask\User\Infrastructure\Repository\UserRepository::create(Kptask\User\Domain\Entity\User $userModel) must be compatible with Kptask\Core\Repository\UserRepositoryInterface::create(Kptask\User\Entity\User $user) {"code":64,"message":"Declaration of Kptask\\User\\Infrastructure\\Repository\\UserRepository::create(Kptask\\User\\Domain\\Entity\\User $userModel) must be compatible with Kptask\\Core\\Repository\\UserRepositoryInterface::create(Kptask\\User\\Entity\\User $user)","file":"/vagrant/kptask/src/User/src/Infrastructure/Repository/UserRepository.php","line":15,"trace":null} []
[2020-05-12 17:13:14] skeletonlog.ERROR: Uncaught Exception TypeError: "Argument 2 passed to Kptask\User\Domain\Validator\UserValidator::__construct() must be an instance of Kptask\Core\Repository\UserRepositoryInterface, instance of Kptask\User\Infrastructure\Repository\UserRepository given, called in /vagrant/kptask/config/bootstrap.php on line 189" at /vagrant/kptask/src/User/src/Domain/Validator/UserValidator.php line 32 {"exception":"[object] (TypeError(code: 0): Argument 2 passed to Kptask\\User\\Domain\\Validator\\UserValidator::__construct() must be an instance of Kptask\\Core\\Repository\\UserRepositoryInterface, instance of Kptask\\User\\Infrastructure\\Repository\\UserRepository given, called in /vagrant/kptask/config/bootstrap.php on line 189 at /vagrant/kptask/src/User/src/Domain/Validator/UserValidator.php:32)"} []
[2020-05-12 17:14:42] skeletonlog.ERROR: Uncaught Exception TypeError: "Argument 1 passed to Kptask\User\Domain\Validator\UserValidationManager::__construct() must be an instance of Kptask\Core\Repository\UserRepositoryInterface, instance of Kptask\User\Infrastructure\Repository\UserRepository given, called in /vagrant/kptask/config/bootstrap.php on line 194" at /vagrant/kptask/src/User/src/Domain/Validator/UserValidationManager.php line 36 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Kptask\\User\\Domain\\Validator\\UserValidationManager::__construct() must be an instance of Kptask\\Core\\Repository\\UserRepositoryInterface, instance of Kptask\\User\\Infrastructure\\Repository\\UserRepository given, called in /vagrant/kptask/config/bootstrap.php on line 194 at /vagrant/kptask/src/User/src/Domain/Validator/UserValidationManager.php:36)"} []
[2020-05-12 17:25:46] skeletonlog.ERROR: Uncaught Exception Error: "Class 'Kptask\User\Validator\EmailValidator' not found" at /vagrant/kptask/src/User/src/Domain/Validator/UserValidationManager.php line 52 {"exception":"[object] (Error(code: 0): Class 'Kptask\\User\\Validator\\EmailValidator' not found at /vagrant/kptask/src/User/src/Domain/Validator/UserValidationManager.php:52)"} []
[2020-05-12 17:29:02] skeletonlog.ERROR: Uncaught Exception Error: "Class 'Kptask\User\Entity\User' not found" at /vagrant/kptask/src/Core/src/Factory/AbstractDomainFactory.php line 22 {"exception":"[object] (Error(code: 0): Class 'Kptask\\User\\Entity\\User' not found at /vagrant/kptask/src/Core/src/Factory/AbstractDomainFactory.php:22)"} []
